### ISSUE TITLE
Fails to build on 64 bit Haiku

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Hare#15]
Welcome to the Haiku shell.

~/HaikuArchives/Hare> build.sh
Starting Build of Hare
Building Hare Library
Error: Failed to find paths: No such file or directory
g++ -c src/libHare/ID3Tag.cpp -iquote./  -iquotesrc/libHare/   -O3    -o "objects_libhare/ID3Tag.o"
In file included from src/libHare/ID3Tag.cpp:4:0:
src/libHare/ID3Tag.h:7:21: fatal error: fileref.h: No such file or directory
compilation terminated.
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects_libhare/ID3Tag.o' failed
make: *** [objects_libhare/ID3Tag.o] Error 1
Building Encoders
make[1]: Entering directory '/boot/home/HaikuArchives/Hare/src/Encoders/BeEncoder'
Error: Failed to find paths: No such file or directory
g++ -c BeEncoder.cpp -iquote./  -iquote./  -iquote../../libHare   -O3    -o "objects_encoder/BeEncoder.o"
In file included from ../../libHare/ID3Tags.h:7:0,
                 from BeEncoder.cpp:16:
../../libHare/ID3Tag.h:7:21: fatal error: fileref.h: No such file or directory
compilation terminated.
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects_encoder/BeEncoder.o' failed
make[1]: *** [objects_encoder/BeEncoder.o] Error 1
make[1]: Leaving directory '/boot/home/HaikuArchives/Hare/src/Encoders/BeEncoder'
Makefile_Encoders:8: recipe for target 'all' failed
make: *** [all] Error 2
Building Hare
cc -o "objects_hare/Hare"       objects_hare/Application.o objects_hare/AppView.o objects_hare/AppWindow.o objects_hare/CheckMark.o objects_hare/EditorView.o objects_hare/EncoderListView.o objects_hare/FileNamePatternView.o objects_hare/RefRow.o objects_hare/Settings.o objects_hare/StatusBarFilter.o -g -Xlinker -soname=_APP_  -Lobjects_hare/  -Lsrc/Hare/  -Lobjects_libhare    -lstdc++  -lsupc++  -lhare  -ltag  -lbe  -lgame  -lmedia  -ltracker  -lcolumnlistview 
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/5.4.0/../../../../x86_64-unknown-haiku/bin/ld: cannot find -lhare
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/5.4.0/../../../../x86_64-unknown-haiku/bin/ld: cannot find -ltag
collect2: error: ld returned 1 exit status
/boot/system/develop/etc/makefile-engine:246: recipe for target 'objects_hare/Hare' failed
make: *** [objects_hare/Hare] Error 1
Moving final executable and encoders into dist folder
cp: cannot stat 'objects_hare/Hare': No such file or directory
cp: cannot stat 'src/Encoders/BeEncoder/objects_encoder/BeEncoder': No such file or directory
cp: cannot stat 'src/Encoders/M3UCreator/objects_encoder/M3U-Creator': No such file or directory
cp: cannot stat 'src/Encoders/MP3GoGo/objects_encoder/MP3-GoGo': No such file or directory
cp: cannot stat 'src/Encoders/MP3Lame/objects_encoder/MP3-Lame': No such file or directory
cp: cannot stat 'src/Encoders/OGGEncoder/objects_encoder/OGG-Encoder': No such file or directory
The Build has Finished!
~/HaikuArchives/Hare>

**Comment by Vidrep** [comment]
HARE also fails on x86_gcc2h. Both times using the supplied build script.

**Comment by Vidrep** [comment]
Welcome to the Haiku shell.

~/HaikuArchives/Hare> build.sh
Starting Build of Hare
Building Hare Library
mkdir -p objects_libhare; \
mkdepend  -Isrc/libHare/ -p .cpp:objects_libhare/%n.o -m -f "objects_libhare/ID3Tags.d" src/libHare/ID3Tags.cpp
mkdir -p objects_libhare; \
mkdepend  -Isrc/libHare/ -p .cpp:objects_libhare/%n.o -m -f "objects_libhare/ID3Tag.d" src/libHare/ID3Tag.cpp
mkdir -p objects_libhare; \
mkdepend  -Isrc/libHare/ -p .cpp:objects_libhare/%n.o -m -f "objects_libhare/GenreList.d" src/libHare/GenreList.cpp
mkdir -p objects_libhare; \
mkdepend  -Isrc/libHare/ -p .cpp:objects_libhare/%n.o -m -f "objects_libhare/AudioInfo.d" src/libHare/AudioInfo.cpp
mkdir -p objects_libhare; \
mkdepend  -Isrc/libHare/ -p .cpp:objects_libhare/%n.o -m -f "objects_libhare/AudioAttributes.d" src/libHare/AudioAttributes.cpp
mkdir -p objects_libhare; \
mkdepend  -Isrc/libHare/ -p .cpp:objects_libhare/%n.o -m -f "objects_libhare/AudioAttribute.d" src/libHare/AudioAttribute.cpp
mkdir -p objects_libhare; \
mkdepend  -Isrc/libHare/ -p .cpp:objects_libhare/%n.o -m -f "objects_libhare/AEEncoder.d" src/libHare/AEEncoder.cpp
Error: Failed to find paths: No such file or directory
g++ -c src/libHare/AEEncoder.cpp  -Isrc/libHare/ -I-   -O3    -o "objects_libhare/AEEncoder.o"
Error: Failed to find paths: No such file or directory
g++ -c src/libHare/AudioAttribute.cpp  -Isrc/libHare/ -I-   -O3    -o "objects_libhare/AudioAttribute.o"
Error: Failed to find paths: No such file or directory
g++ -c src/libHare/AudioAttributes.cpp  -Isrc/libHare/ -I-   -O3    -o "objects_libhare/AudioAttributes.o"
Error: Failed to find paths: No such file or directory
g++ -c src/libHare/AudioInfo.cpp  -Isrc/libHare/ -I-   -O3    -o "objects_libhare/AudioInfo.o"
Error: Failed to find paths: No such file or directory
g++ -c src/libHare/GenreList.cpp  -Isrc/libHare/ -I-   -O3    -o "objects_libhare/GenreList.o"
Error: Failed to find paths: No such file or directory
g++ -c src/libHare/ID3Tag.cpp  -Isrc/libHare/ -I-   -O3    -o "objects_libhare/ID3Tag.o"
In file included from /boot/home/HaikuArchives/Hare/src/libHare/ID3Tag.cpp:4:
/boot/home/HaikuArchives/Hare/src/libHare/ID3Tag.h:7: fileref.h: No such file or directory
/boot/home/HaikuArchives/Hare/src/libHare/ID3Tag.h:8: tag.h: No such file or directory
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects_libhare/ID3Tag.o' failed
make: *** [objects_libhare/ID3Tag.o] Error 1
Building Encoders
make[1]: Entering directory '/boot/home/HaikuArchives/Hare/src/Encoders/BeEncoder'
mkdir -p objects_encoder; \
mkdepend  -I./  -I../../libHare -p .cpp:objects_encoder/%n.o -m -f "objects_encoder/MediaMenuItem.d" MediaMenuItem.cpp
mkdir -p objects_encoder; \
mkdepend  -I./  -I../../libHare -p .cpp:objects_encoder/%n.o -m -f "objects_encoder/BeEncoder.d" BeEncoder.cpp
Error: Failed to find paths: No such file or directory
g++ -c BeEncoder.cpp  -I./  -I../../libHare -I-   -O3    -o "objects_encoder/BeEncoder.o"
In file included from /boot/home/HaikuArchives/Hare/src/libHare/ID3Tags.h:7,
                 from /boot/home/HaikuArchives/Hare/src/Encoders/BeEncoder/BeEncoder.cpp:16:
/boot/home/HaikuArchives/Hare/src/libHare/ID3Tag.h:7: fileref.h: No such file or directory
/boot/home/HaikuArchives/Hare/src/libHare/ID3Tag.h:8: tag.h: No such file or directory
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects_encoder/BeEncoder.o' failed
make[1]: *** [objects_encoder/BeEncoder.o] Error 1
make[1]: Leaving directory '/boot/home/HaikuArchives/Hare/src/Encoders/BeEncoder'
Makefile_Encoders:8: recipe for target 'all' failed
make: *** [all] Error 2
Building Hare
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/StatusBarFilter.d" src/Hare/StatusBarFilter.cpp
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/Settings.d" src/Hare/Settings.cpp
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/RefRow.d" src/Hare/RefRow.cpp
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/FileNamePatternView.d" src/Hare/FileNamePatternView.cpp
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/EncoderListView.d" src/Hare/EncoderListView.cpp
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/EditorView.d" src/Hare/EditorView.cpp
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/CheckMark.d" src/Hare/CheckMark.cpp
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/AppWindow.d" src/Hare/AppWindow.cpp
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/AppView.d" src/Hare/AppView.cpp
mkdir -p objects_hare; \
mkdepend  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -p .cpp:objects_hare/%n.o -m -f "objects_hare/Application.d" src/Hare/Application.cpp
g++ -c src/Hare/Application.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/Application.o"
g++ -c src/Hare/AppView.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/AppView.o"
g++ -c src/Hare/AppWindow.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/AppWindow.o"
g++ -c src/Hare/CheckMark.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/CheckMark.o"
g++ -c src/Hare/EditorView.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/EditorView.o"
g++ -c src/Hare/EncoderListView.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/EncoderListView.o"
g++ -c src/Hare/FileNamePatternView.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/FileNamePatternView.o"
g++ -c src/Hare/RefRow.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/RefRow.o"
g++ -c src/Hare/Settings.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/Settings.o"
g++ -c src/Hare/StatusBarFilter.cpp  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   -o "objects_hare/StatusBarFilter.o"
cat src/Hare/Hare.rdef | cc -E  -Iobjects_hare/  -Isrc/Hare/  -Isrc/libHare -I-  -I/boot/system/develop/headers/private/interface  -O0 -g   - | grep -av '^#' | rc -I src/Hare/ -o "objects_hare/Hare.rsrc" -
cc -o "objects_hare/Hare"       objects_hare/Application.o objects_hare/AppView.o objects_hare/AppWindow.o objects_hare/CheckMark.o objects_hare/EditorView.o objects_hare/EncoderListView.o objects_hare/FileNamePatternView.o objects_hare/RefRow.o objects_hare/Settings.o objects_hare/StatusBarFilter.o -g -Xlinker -soname=_APP_  -Lobjects_hare/  -Lsrc/Hare/  -Lobjects_libhare    -lstdc++.r4  -lhare  -ltag  -lbe  -lgame  -lmedia  -ltracker  -lcolumnlistview 
/packages/gcc-2.95.3_2017_07_20-1/.self/develop/tools/i586-pc-haiku/bin/ld: cannot find -lhare
collect2: ld returned 1 exit status
/boot/system/develop/etc/makefile-engine:246: recipe for target 'objects_hare/Hare' failed
make: *** [objects_hare/Hare] Error 1
Moving final executable and encoders into dist folder
cp: cannot stat 'objects_hare/Hare': No such file or directory
cp: cannot stat 'src/Encoders/BeEncoder/objects_encoder/BeEncoder': No such file or directory
cp: cannot stat 'src/Encoders/M3UCreator/objects_encoder/M3U-Creator': No such file or directory
cp: cannot stat 'src/Encoders/MP3GoGo/objects_encoder/MP3-GoGo': No such file or directory
cp: cannot stat 'src/Encoders/MP3Lame/objects_encoder/MP3-Lame': No such file or directory
cp: cannot stat 'src/Encoders/OGGEncoder/objects_encoder/OGG-Encoder': No such file or directory
The Build has Finished!
~/HaikuArchives/Hare>

**Comment by humdingerb** [comment]
Works here under 32bit. Maybe a missing dependency? Have you installed devel:libtag ?

**Comment by Vidrep** [comment]
I installed all the libid3tag devel packages and tried again. Same - build fails.

**Comment by Vidrep** [comment]
OK, got it built on 64 bit. Now the fun begins.
