### ISSUE TITLE
Loaded CD is not read - Fix keyboard shortcut

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Hare#16]
File->Load CD->Audio CD
Content is not loaded into track list

**Comment by scottmc** [comment]
@Vidrep can you rebuild with the current code and see if this is still the case?

**Comment by Vidrep** [comment]
Progress! I was only able to load via drag and drop. 
![hare](https://user-images.githubusercontent.com/13264393/37007130-15f43f9a-2099-11e8-87b0-4db5ed440857.png)

**Comment by Vidrep** [comment]
Using drag and drop works well enough. I would have thought that selecting the CD from the drop down menu would work as well, but clicking or CTL ALT 1 does nothing currently.

**Comment by scottmc** [comment]
Can you retest this with the latest code?

**Comment by Vidrep** [comment]
Clicking with the mouse works now, but the keyboard shortcut CTL ALT 1 is still not working.
