### ISSUE TITLE
Output directory is not created

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/Hare#17]
Example: /boot/home/MP3->"Apply"
Output directory is not created

**Comment by janus2** [comment]
Did you mean the Apply button in File Path and Name Pattern?
That button just changes the contents of the column "Save As". Only during the Encoding, that path is used.

**Comment by Vidrep** [comment]
Until we can actually encode something we won't know if the directory actually gets created.

**Comment by Vidrep** [comment]
Choosing Encoder->M3U Creator works. The output directory and playlist are both created.
Closing as fixed.
