### ISSUE TITLE
Layout issues - Fix details editing

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/Hare#24]
First off, excellent progress on the layout improvements.  Few more issues I'd like to see cleaned up.  
When program first starts up, the text in the File Path view is cropped.  Perhaps arrange the options into one list on the left hand side, break the "Name Pattern" and "File Path" into two text displays, put the FilePath above the NamePattern, this reduces the need for the File Path view to be taking up 50% of the overall window, allowing more space for the Details Editor view.  Also the File Path and Name Pattern text views should be labeled.  On first startup perhaps set the default width for "File Path and Name Pattern" view to 40%?

On the Details View, try to reduce the space between the entries, there's a lot of wasted space there.  Keep in mind that the number of detail entries is likely to increase once we add support for more tags.  This will eventually require a scrolling view.  Figure there will be an entry for Album Art and more.

**Comment by scottmc** [comment]
![hare-markup3](https://user-images.githubusercontent.com/1039279/37109960-6953e322-21f0-11e8-897f-0f1f801b1e8a.png)

**Comment by scottmc** [comment]
@CodeforEvolution These might be easy changes?

**Comment by Vidrep** [comment]
I propose going even further and putting the name pattern etc into settings dialog from a menu selection. The interface could use a lot of clean up to keep it simple and functional.

**Comment by scottmc** [comment]
perhaps create a mockup and post here

**Comment by janus2** [comment]
My take...
![hare](https://user-images.githubusercontent.com/10423645/37245289-29cb251e-2496-11e8-831e-f810a044cafa.gif)

**Comment by Vidrep** [comment]
That's an improvement. Having to manually type %n etc is a little too geeky for the average end user. One step at a time...

**Comment by janus2** [comment]
What is the alternative?

**Comment by humdingerb** [comment]
Maybe have "Artist=%a" etc. as some kinda widget that can be dragged onto the text control. Then people can still go the keyboard-only route or just quickly drag&drop their naming parameters. Change mouse pointer when on d&d-widget.

**Comment by Vidrep** [comment]
That's where the one step at a time comes in...we leave it like you have it until a solution is thought out. Anyway, it looks way better. Great job!

**Comment by Vidrep** [comment]
Have a look at the Preferences->Naming method used by UltraEncode.https://github.com/HaikuArchives/UltraEncode/issues/1

**Comment by janus2** [comment]
It's much worst... is not versatile like Hare 👎

**Comment by Vidrep** [comment]
I think you can push your change now, just as it is, until we can all agree on the best solution for the naming convention.

**Comment by humdingerb** [comment]
How about reducing the vertical spacing between the text controls of the "Details editor"?

**Comment by Vidrep** [comment]
Here is what Hare looks like after loading an audio CD:
https://ibb.co/c3Ntq7

**Comment by Vidrep** [comment]
How about further discussion on IRC #haiku-3rdparty?

**Comment by CodeforEvolution** [comment]
Should I attempt to code @janus2's suggested design? Or should I submit a pull request with @scottmc's design that I've already coded.

**Comment by janus2** [comment]
@CodeforEvolution we can open 2 PR so other participants can play with the two solutions.
Mine is far from perfect, is just an attempt to merge the suggestions of @Vidrep and @scottmc in one solution. We can always integrate the 2 PR.

**Comment by smccrearyx** [comment]
What about a tabbed view instead?  With the Filelist on the first tab, File Path and Name Pattern on second tab, and details editor on the third tab?  This would allow the window to be even smaller and still be able to see the info the user really cares about.  I'd still like to see FilePath and Name Pattern text box split into two.

**Comment by scottmc** [comment]
What about a tabbed view instead? With the Filelist on the first tab, File Path and Name Pattern on second tab, and details editor on the third tab? This would allow the window to be even smaller and still be able to see the info the user really cares about. I'd still like to see FilePath and Name Pattern text box split into two.  I'll merge the current PR.  Then you can look into how a tabbed view might work if you like.

**Comment by scottmc** [comment]
I'll try to take a look at both PRs and see if either is what we should go with, or try a tabbed version or something else.  Perhaps @humdingerb or @diversys has an opinion on which GUI would be better here?

**Comment by Vidrep** [comment]
Having looked at, and used both versions, I must say that I prefer the separate entries for file path and file pattern, but integrated into the layout Janus2 used (a melding of the two layouts).
The way that "Save as" is displayed, is much too long if we also include the path info. I propose only showing the final track naming there (See screenshots).
https://ibb.co/ifEjkH
https://ibb.co/iyHWXx

**Comment by janus2** [comment]
I'm working on BePodder and I did not have the time to try the second PR. But I have a question, with the split TextControls is it possible to use the substitution to use different folders for different encodings?

**Comment by Vidrep** [comment]
Do you mean, for example:  encode track 1 as mp3 in one directory, and encode track 2 as flac in a second directory? The answer is 'no", not currently. Once you click "apply" all tracks are tagged the same.

**Comment by janus2** [comment]
What I would like is to organize my music collection with ~/Music/<genre>/<author>/<album>/<title>-<track id>.mp3
Can I still doing this with the split textcontrol?

**Comment by CodeforEvolution** [comment]
@janus2 You should be able to do that still with the split text control.

**Comment by humdingerb** [comment]
Mockup (no more github uploads with Haiku browsers...): https://lut.im/2rnp8zfauO/kBrTkyHFQtnByo94.png

Maybe even have 3 columns with the %variables in the "File path/Name pattern" and arrange vertically?
If not, I'd say switch left/right panels (File path <-> Details editor).

**Comment by CodeforEvolution** [comment]
After 2 months, where do we stand exactly?

**Comment by scottmc** [comment]
@CodeforEvolution have any time to try out what I proposed above?

**Comment by CodeforEvolution** [comment]
I have tried it out, I created a branch called "simplelayout" on my github: https://github.com/CodeforEvolution/Hare
The one thing, is that I can't get the scrollbar to resize correctly, it seems it hasn't been adapted to the layout api yet.

**Comment by CodeforEvolution** [comment]
I have updated my "simplelayout" branch on my github with some fixes. Feel free to check it out!
@scottmc @Vidrep @janus2

**Comment by scottmc** [comment]
@CodeforEvolution I like it.  But yes, the scroll bar issue would need to be figured out.  Perhaps open a trac ticket on Haiku to report it.  The preferenced dialog box is a nice solution, perhaps check it with a /really/long/album/name/and/song/name to see how the wide looks.  I suspect it's fine, but you may want to make the default width different after checking it.  Also check the whole program's layout with the system font set to 8 and again at 18 and see if it reacts as well as expected.
Nice work so far.

**Comment by CodeforEvolution** [comment]
I have made sure to check font sizes, and ay ok! I also managed to fix the scrollbar bug, had to do with calls to SetExplicitMin/MaxSize() to fix. Besides that, should I open a pull request? I'd say this major overall would fix a lot of functionality in Hare.

**Comment by scottmc** [comment]
Yes, please open a new pull request.

**Comment by scottmc** [comment]
Ok, merged code.  Let's move forward from here.  Can you update the readme.md screenshot?

**Comment by scottmc** [comment]
I tried this latest code, installed an audio cd in my cd-rom drive and Haiku detected it.  I then dragged the contents to Hare and dropped them, this worked and it populated the file list.  But the details editor did not allow any editing.  I also tried File>LoadCD and that loads as expected, but still not able to edit details.

**Comment by scottmc** [comment]
Any takers on fixing the details editing?

**Comment by scottmc** [comment]
The layout looks mostly good now, but I can't fully check it, as it's not finding any of the encoders for me now.  See issue #34 .  I have submitted a pull request to add MIT headers where needed and some other minor cleanups.  There shouldn't be anything in it that will break the build.  It builds ok using Haiku R1B3 for gcc2h and x64.

**Comment by scottmc** [comment]
![preferences-selector-mockup](https://user-images.githubusercontent.com/1039279/141029435-9c48191c-afd6-4cd2-9dd9-8923fda9aa51.png)
Expanding on the previous mock-up, this one shows how it might be interactive. You pick the base directory using a file selection control, to store the output files, then create the subdirectory structures by putting the directory items in the order you want them.  Then do the same for the output filename, put them in the order you want then.  Want a specific separator style?  Pick it from a drop down menu.  Want a custom one? Maybe hide that in a config file for those who like the flexibility, and if it's listed in the config file add it to the drop down as an option as well.  The extension would default to the one that corresponds to the encoder picked, perhaps allow this to be overridden as well in a config file?  You could also pick NONE here if you'd like no extension.
The output directory and output filename textviews would automatically populate based on your picks from the columnlistviews and drop down menus.

By default, the entries would be something like what you see in this mock-up, so if a user doesn't set them, they will still get sane results.

**Comment by scottmc** [comment]
closing this one, this is mostly complete, just need to address the preferences which can be done in #41
