### ISSUE TITLE
Add filename character swap out option to preferences

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/Hare#49]
Same issue as Calendar had, an attempt to put a / in the filename will result in chaos.  Substitute the division slash whenever a / is in the song title.
See https://github.com/HaikuArchives/Calendar/pull/96

**Comment by scottmc** [comment]
Ran into a CD with this issue.  Panic! at The Disco's Too Weird to Live, Too Rare to Die! track 6 song name is "Girls / Girls / Boys", after encoding, I found the resulting mp3 2 sub-directories down.

**Comment by scottmc** [comment]
Note track 6, the Audio CD lookup by Haiku replaces the slashes with a dash as seen in the File column.  This solution replaces the slash with the divisional slash as seen in the Save As column.  This could later be added as a preferences option, giving the user the ability to pick what char to replace the slash with.  But for now just put in the division slash.

![Slash-Subbed](https://user-images.githubusercontent.com/1039279/142129287-1783ea65-f071-415e-8b1f-e5242ddfcc1a.png)

**Comment by humdingerb** [comment]
It may be worth sticking with normal ASCII characters for replacement. Someone may have to type out a filename for some reason or use some antique file system that doesn't support those exotic characters.

**Comment by scottmc** [comment]
I guess the target output for this program isn't always going to be for BeFS, but songs could end up on other systems, such as phones, tablets, rokus, cars, etc.  So probably need to cover more cases than just slash.  Likely have to swap out any chars that can trip up these others.  Things like ? and * might fail on windows for instance.  I'll hold off on this one and see if I can make a fuller list of chars that can trip things up.  Found another good test CD, R.E.M. gives a test for .,?'  What to replace these with?  I'm leaning towards having this be a configurable option in the preferences.  Some users might prefer underscores, others dashes, while other might like to have alternate unicode characters that look like what they are replacing.

![questionmark-period-comma-test2](https://user-images.githubusercontent.com/1039279/142483027-6cd1d2f2-a7ec-4fb6-9da7-e50b0ddcd49c.png)
