### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by baimafeima** [HaikuArchives/Hare#9]
Hello, could you release versioned tarballs here on GitHub?

**Comment by humdingerb** [comment]
GitHub does that anyway, e.g. for current commit
http://github.com/HaikuArchives/Hare/archive/2a5eda8b6428f41f4ce4093e9bc9aeb7f15bb58a.tar.gz

**Comment by baimafeima** [comment]
Tagging releases would have several advantages. You could also make the changelog directly visible in your GitHub releases. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by humdingerb** [comment]
I've now created a "first" release v1.1.1. Future releases should then add a changelog, maybe with that log generator.
I still think releases only make sense with active projects. This one has had only tiny contributions for a while. Making a new release for an added icon etc. is a bit silly. Easier to  point the haikuporter recipe to the latest commit and increase the recipe's REVISION to trigger the build of a new hpkg.
